config/routes.rb
Tickety::Application.routes.draw do

  get "password_resets/create"

  get "password_resets/edit"

  get "password_resets/update"

resources :password_resets

  resources :rewards do
get :redeem, :on => :collection
post :redeem, :on => :collection
end

  match 'home' => "pages#index"
  match 'newreleases' => "pages#newreleases"
  match 'currentlyshowing' => "pages#currentlyshowing"
  match 'rewardsystem' => "pages#customer_reward"
  match 'signin' => "pages#signin"
  match 'policies' => "pages#policies"
  match 'creators' => "pages#creators"
  match 'webinfo' => "pages#webinfo"
  match 'admindashboard' => "pages#admindashboard"
  
  root :to => "pages#index"

resources :movies do
get :auto_complete_for_movie_title , :on => :collection
end

 resources :bookings do
get :getCinema , :on => :collection
get :prebooking , :on => :collection
    end

  resources :movies
  
  resources :searches

  resources :payments

  resources :theaters

  resources :seats

  resources :cinemas

  resources :shows do
get :updateshows, :on => :collection
end

  resources :bookings

resources :user_sessions
resources :users
  
match 'login' => 'user_sessions#new', :as => :login
match 'logout' => 'user_sessions#destroy', :as => :logout

match 'signup',  to: 'user#new'

  resources :users

end

app/models/seat.rb
class Seat < ActiveRecord::Base
  attr_accessible :booking_id, :is_taken, :number, :theater_id, :type, :show_id
belongs_to :theater
belongs_to :booking
belongs_to :show
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  load_and_authorize_resource
  # GET /seats
  # GET /seats.json
  def index
    @seats = Seat.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @seats }
    end
  end

  # GET /seats/1
  # GET /seats/1.json
  def show
    @seat = Seat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @seat }
    end
  end

  # GET /seats/new
  # GET /seats/new.json
  def new
    @seat = Seat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @seat }
    end
  end

  # GET /seats/1/edit
  def edit
    @seat = Seat.find(params[:id])
  end

  # POST /seats
  # POST /seats.json
  def create
    @seat = Seat.new(params[:seat])

    respond_to do |format|
      if @seat.save
        format.html { redirect_to @seat, notice: 'Seat was successfully created.' }
        format.json { render json: @seat, status: :created, location: @seat }
      else
        format.html { render action: "new" }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /seats/1
  # PUT /seats/1.json
  def update
    @seat = Seat.find(params[:id])

    respond_to do |format|
      if @seat.update_attributes(params[:seat])
        format.html { redirect_to @seat, notice: 'Seat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seats/1
  # DELETE /seats/1.json
  def destroy
    @seat = Seat.find(params[:id])
    @seat.destroy

    respond_to do |format|
      format.html { redirect_to seats_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/seats/_form.html.erb
<%= form_for(@seat) do |f| %>
  <% if @seat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
      <% @seat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="large-12 columns">
      <label>Number</label>
    <%= f.number_field :number %>
    </div>
  </div>

  <div class="row">
    <div class="large-12 columns">
      <label>Type</label>
    <%= f.text_field :type %>
    </div>
  </div>

  <div class="row">
    <div class="large-12 columns">
      <label>Theatre ID</label>
    <%= f.number_field :theater_id %>
    </div>
  </div>

  <div class="row">
    <div class="large-12 columns">
      <label>Taken?</label>
    <%= f.check_box :is_taken %>
    </div>
  </div>


  <div class="row">
    <div class="large-12 columns">
      <label>Booking ID</label>
    <%= f.number_field :booking_id %>
    </div>
  </div>

<br/>
<br/>
<center>
<input type="Submit" value="Submit" class="button"> 
</center>
<% end %>

app/views/seats/edit.html.erb
<center>
<h1>Editing seat</h1>
</center>
<%= render 'form' %>
<center>
<%= link_to 'Show', @seat %> |
<%= link_to 'Back', seats_path %>
</center>

app/views/seats/index.html.erb
<center>
<h1>Listing seats</h1>

<table>
  <tr>
    <th>Number</th>
    <th>Type</th>
    <th>Theater</th>
    <th>Is taken</th>
    <th>Booking</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @seats.each do |seat| %>
  <tr>
    <td><%= seat.number %></td>
    <td><%= seat.type %></td>
    <td><%= seat.theater_id %></td>
    <td><%= seat.is_taken %></td>
    <td><%= seat.booking_id %></td>
    <td><%= link_to 'Show', seat %></td>
    <td><%= link_to 'Edit', edit_seat_path(seat) %></td>
    <td><%= link_to 'Destroy', seat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<% if can? :manage, @seat %>
<%= link_to 'New Seat', new_seat_path, :class => 'button' %>
<% end %>
</center>

app/views/seats/new.html.erb
<center>
<h1>New seat</h1>
</center>
<%= render 'form' %>

app/views/seats/show.html.erb
<div class="row">
<div class="small-2 large-4 columns">
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @seat.number %>
</p>

<p>
  <b>Type:</b>
  <%= @seat.type %>
</p>

<p>
  <b>Theater:</b>
  <%= @seat.theater_id %>
</p>

<p>
  <b>Is taken:</b>
  <%= @seat.is_taken %>
</p>

<p>
  <b>Booking:</b>
  <%= @seat.booking_id %>
</p>
</div>
</div>
<center>
<%= link_to 'Edit', edit_seat_path(@seat) %> |
<%= link_to 'Back', seats_path %>
</center>