config/routes.rb
Tickety::Application.routes.draw do

  get "password_resets/create"

  get "password_resets/edit"

  get "password_resets/update"

resources :password_resets

  resources :rewards do
get :redeem, :on => :collection
post :redeem, :on => :collection
end

  match 'home' => "pages#index"
  match 'newreleases' => "pages#newreleases"
  match 'currentlyshowing' => "pages#currentlyshowing"
  match 'rewardsystem' => "pages#customer_reward"
  match 'signin' => "pages#signin"
  match 'policies' => "pages#policies"
  match 'creators' => "pages#creators"
  match 'webinfo' => "pages#webinfo"
  match 'admindashboard' => "pages#admindashboard"
  
  root :to => "pages#index"

resources :movies do
get :auto_complete_for_movie_title , :on => :collection
end

 resources :bookings do
get :getCinema , :on => :collection
get :prebooking , :on => :collection
    end

  resources :movies
  
  resources :searches

  resources :payments

  resources :theaters

  resources :seats

  resources :cinemas

  resources :shows do
get :updateshows, :on => :collection
end

  resources :bookings

resources :user_sessions
resources :users
  
match 'login' => 'user_sessions#new', :as => :login
match 'logout' => 'user_sessions#destroy', :as => :logout

match 'signup',  to: 'user#new'

  resources :users

end

app/models/reward.rb
class Reward < ActiveRecord::Base
  attr_accessible :reward_points, :reward_title
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  # GET /rewards
  # GET /rewards.json
  def index
    @rewards = Reward.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rewards }
    end
  end

  # GET /rewards/1
  # GET /rewards/1.json
  def show
    @reward = Reward.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reward }
    end
  end

  # GET /rewards/new
  # GET /rewards/new.json
  def new
    @reward = Reward.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reward }
    end
  end

  # GET /rewards/1/edit
  def edit
    @reward = Reward.find(params[:id])
  end

  # POST /rewards
  # POST /rewards.json
  def create
    @reward = Reward.new(params[:reward])

    respond_to do |format|
      if @reward.save
        format.html { redirect_to @reward, notice: 'Reward was successfully created.' }
        format.json { render json: @reward, status: :created, location: @reward }
      else
        format.html { render action: "new" }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rewards/1
  # PUT /rewards/1.json
  def update
    @reward = Reward.find(params[:id])

    respond_to do |format|
      if @reward.update_attributes(params[:reward])
        format.html { redirect_to @reward, notice: 'Reward was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rewards/1
  # DELETE /rewards/1.json
  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy

    respond_to do |format|
      format.html { redirect_to rewards_url }
      format.json { head :no_content }
    end
  end

  def redeem
    @reward = Reward.find(params[:id])
    @user = current_user
    @user.reward_points = @user.reward_points - @reward.reward_points
    respond_to do |format|
      @user.save
      format.html { redirect_to rewardsystem_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= form_for(@reward) do |f| %>
  <% if @reward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
      <% @reward.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reward_title %><br />
    <%= f.text_field :reward_title %>
  </div>
  <div class="field">
    <%= f.label :reward_points %><br />
    <%= f.number_field :reward_points %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rewards/edit.html.erb
<h1>Editing reward</h1>

<%= render 'form' %>

<%= link_to 'Show', @reward %> |
<%= link_to 'Back', rewards_path %>

app/views/rewards/index.html.erb
<h1>Listing rewards</h1>

<table>
  <tr>
    <th>Reward title</th>
    <th>Reward points</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rewards.each do |reward| %>
  <tr>
    <td><%= reward.reward_title %></td>
    <td><%= reward.reward_points %></td>
    <td><%= link_to 'Show', reward %></td>
    <td><%= link_to 'Edit', edit_reward_path(reward) %></td>
    <td><%= link_to 'Destroy', reward, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reward', new_reward_path %>

app/views/rewards/new.html.erb
<h1>New reward</h1>

<%= render 'form' %>

<%= link_to 'Back', rewards_path %>

app/views/rewards/show.html.erb
<head>
	<link href="/assets/style.css" rel="stylesheet" type="text/css" />
	</head>
<p id="notice"><%= notice %></p>
<center>
	</br></br></br></br></br></br></br></br>
<div class="row">
   <div class="large-9 small-centered columns">


     <!-- Header Content -->


           <h3 class="show-for-small">Header<hr/></h3>

           <div class="panel">
             <h4 class="hide-for-small">What does this mean?<hr/></h4>
           <h5 class="subheader">With every point to gain from using this system, you can collect enough and get free popcorn, free drinks, and even free tickets! All you have to do is take your coupon to the cinema and enjoy your sweet reward!</h5></br>
           </div>

<div class="panel">

		<div class="row" style="padding-top: 10px;">
	      <div class="large-4 columns">
	    		<img class="morph" style="margin-bottom: 10px;" src="/assets/popcorn.png">
	      </div>
	      <div class="large-4 columns">
	    		<img class="morph" style="margin-bottom: 10px;" src="/assets/drink.png">
	      </div>
	      <div class="large-4 columns">
	    		<img class="morph" style="margin-bottom: 10px;" src="/assets/freeticket.png">
	    	</div>
	    </div> </br>

</div>

         <div class="row">
             <div class="large-6 small-6 columns">
               <div class="panel">
                 <h5>Reward Type</h5>
               <h6 class="subheader"><%= @reward.reward_title %></h6></br>
               </div>
             </div>

             <div class="large-6 small-6 columns">
               <div class="panel">
                 <h5>Reward Points</h5>
               <h6 class="subheader"><%= @reward.reward_points %></h6></br>
               </div>
             </div>


<%= link_to 'Back', rewardsystem_path, :class=>" button" %>


   </div>
 </div>
</center>
</br></br></br></br></br></br></br></br>
</br></br></br></br></br></br></br></br>
</br></br></br></br></br></br></br></br>
</br></br></br></br></br></br></br></br>