config/routes.rb
Tickety::Application.routes.draw do

  get "password_resets/create"

  get "password_resets/edit"

  get "password_resets/update"

resources :password_resets

  resources :rewards do
get :redeem, :on => :collection
post :redeem, :on => :collection
end

  match 'home' => "pages#index"
  match 'newreleases' => "pages#newreleases"
  match 'currentlyshowing' => "pages#currentlyshowing"
  match 'rewardsystem' => "pages#customer_reward"
  match 'signin' => "pages#signin"
  match 'policies' => "pages#policies"
  match 'creators' => "pages#creators"
  match 'webinfo' => "pages#webinfo"
  match 'admindashboard' => "pages#admindashboard"
  
  root :to => "pages#index"

resources :movies do
get :auto_complete_for_movie_title , :on => :collection
end

 resources :bookings do
get :getCinema , :on => :collection
get :prebooking , :on => :collection
    end

  resources :movies
  
  resources :searches

  resources :payments

  resources :theaters

  resources :seats

  resources :cinemas

  resources :shows do
get :updateshows, :on => :collection
end

  resources :bookings

resources :user_sessions
resources :users
  
match 'login' => 'user_sessions#new', :as => :login
match 'logout' => 'user_sessions#destroy', :as => :logout

match 'signup',  to: 'user#new'

  resources :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
       if user.is_admin?
         can :manage, :all
       elsif user.is_customer?
	       can :read, :all 
	        can [:create, :new], [Booking, Payment]
	        can :prebooking, Booking
 	       cannot :read, Seat
 	       can :update, Seat
        else
          can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  attr_accessible :booking_date, :cinema_id, :customer_id, :movie_id, :payment_id, :show_time

belongs_to :user
belongs_to :payment
belongs_to :show
has_many :seats
end

app/models/cinema.rb
class Cinema < ActiveRecord::Base
  attr_accessible :location, :name
    validates :name, :location, :presence => true
    
has_many :shows, :dependent => :destroy
has_many :theaters, :dependent => :destroy
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :actors, :duration, :genre, :summary, :title, :link
  has_many :shows, :dependent => :destroy
  attr_accessible :movie_image
  has_attached_file :movie_image , :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"

  validates :duration, :numericality => {:greater_than => 0, :only_integer => true, :allow_blank => true, :allow_nil => true}
accepts_nested_attributes_for :shows

  def funky_method
    "#{self.title}"
  end

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  attr_accessor :billing_address, :creditcard_num, :creditcard_type, :CVV
  attr_accessible :amount, :customer_id, :date, :billing_address, :creditcard_num, :creditcard_type, :CVV

  has_many :bookings
  belongs_to :user
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  attr_accessible :reward_points, :reward_title
end

app/models/search.rb
class Search < ActiveRecord::Base
  attr_accessible :movie_title
end

app/models/seat.rb
class Seat < ActiveRecord::Base
  attr_accessible :booking_id, :is_taken, :number, :theater_id, :type, :show_id
belongs_to :theater
belongs_to :booking
belongs_to :show
end

app/models/show.rb
class Show < ActiveRecord::Base
  attr_accessible :cinema_id, :show_date, :show_time, :show_type, :theater_id
has_many :bookings
has_many :seats, :dependent => :destroy
belongs_to :movie
belongs_to :theater
belongs_to :cinema


attr_reader :movie_title
#attr_accessor :movie_title
validates :show_date, :show_time, :theater_id, :movie_title, :show_type, :cinema_id, :movie_title, :presence => true

#attr_reader :movie_title
#attr_accessor :movie_id
attr_accessible :movie_id
attr_accessible :movie_title



def movie_title
  movie.try(:title)
end

def movie_title=(title)
  self.movie = Movie.find_by_title(title) if title.present?
end

def self.clear_show

  t = Time.now
  t2 = t + 15*60
  if t2 > self.show_time
    self.destroy
  end
end

end

app/models/theater.rb
class Theater < ActiveRecord::Base
attr_accessible :cinema_id, :theater_number
attr_accessible :cinema_id, :theater_number
has_many :shows, :dependent => :destroy
has_many :seats, :dependent => :destroy
belongs_to :cinema

attr_accessor           :seat_num
attr_accessible         :seat_num


validates :theater_number, :numericality => {:greater_than => 0, :only_integer => true, :allow_blank => false, :allow_nil => false}

validate do |theater|
  if theater.seat_num == "0"
    theater.errors[:base] << "Please enter the number of seats in the selected theater."
  end
end
scope :for_cinema, lambda{|cinema_id| where('cinema_id = ?', cinema_id)}
end

app/models/user.rb
class User < ActiveRecord::Base
 
  authenticates_with_sorcery!
  attr_accessible :username, :email, :password, :password_confirmation

  validates :name, :presence => true
   validates_format_of :email, :with => /^[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil|biz|info|qa))$/i, :message => "is not a valid format"

  validates_length_of :password, :minimum => 3, :message => "password must be at least 3 characters long", :if => :password
  validates_confirmation_of :password, :message => "should match confirmation", :if => :password
 attr_accessible :billing_address, :creditcard_num, :creditcard_type, :crypted_password, :email, :is_admin, :is_customer, :is_manager, :name, :reward_points, :salt, :security_num, :username

has_many :bookings
has_many :payments
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cinemas_helper.rb
module CinemasHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->

<footer class="footer">


        <p>&copy; 2013 S. Al Hetmi, M. Datta, S. Mustafa, J. Polin. </p>

</footer>

<!-- End Footer -->

app/views/layouts/_header.html.erb
        <div class="nav">
        <ul class="inline-list">
                        <% if current_page?(root_path) == true %>
                <li><a href="#first" class="fade anchorLink">Tickety</a></li>
                        <%else%>
                        <li><a href="/" class="fade anchorLink">Tickety</a></li>
                        <%end%>


                        <% if current_page?(root_path) == true %>
                <li><a href="#space" class="fade anchorLink">Customer Reward</a></li>
                        <%else%>
                        <li><%=link_to "Customer Rewards", rewardsystem_path %></li>
                        <%end%>

                        <% if current_page?(root_path) == true %>
                <li><a href="#desk" class="fade anchorLink">Policies</a></li>
                        <%else%>
                        <li><%= link_to "Website Policies", policies_path %></li>
                        <%end%>



            <% if current_page?(root_path) == true %>
                <li><a href="#kigs" class="fade anchorLink">New Releases</a></li>
                        <%else%>
                        <li><%=link_to "New Releases", newreleases_path %></li>
                        <%end%>


           <li><%=link_to "Currently Showing", currentlyshowing_path %></li>




                <li class="divider hide-for-small"></li>
                                 <% if current_user %>
                                        <% if current_user.is_admin == true %>
                                        <li><%=link_to "Admin Dashboard", admindashboard_path %></li>
                                        <% end %>
<li><%= link_to current_user.name, user_path(current_user.id) %></li>

                                                <li><%= link_to "Logout", :logout %> </li>


                                            <% else %>
                                             <li> <%= link_to "Register", new_user_path %> </li>
                                             <li> <%= link_to "Login", :login %></li>
                                            <% end %>
                                 </li>
        </ul>
                </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>   

</head>
<body>
  <div id="nav">
	<%= render 'layouts/header' %>

  </div>
  <div>
    <p id="notice"><%= notice %></p>
    <p id="alert"><%= alert %></p>
  </div>
  <div class="container">
    <%= yield %>
	<%= render 'layouts/footer' %>
  </div>

</body>
</html>